### PR TITLE
ase v3 support for drupal deployment

### PR DESCRIPTION
**Pull request by haithamshahin333**
Support for deploying bitnami drupal image into private ASE v3

### CODE REVIEW

**Review by rickrain — COMMENTED** [review]
Thanks Haitham!  Have a suggestion - perhaps this should be in a separate repo rather than combined with this one.  The reason I say this, is that, going forward, the assets are going to become more ASEv3 specific.  For example, currently, you're linking over to a tutorial to deploy ASEv3, but, in the near future, we're going to have templates (probably Terraform) to do this.  As such, there will be different requirements and assets to leverage.  And as you pointed out, interacting with the deployed environment is going to be uniquely different as well.

If we keep it as part of this repo, we should probably refactor the README into a high-level summary document describing App Service and ASE, the benefits of each, and then link over to a README for _Drupal on App Service_ and another README for _Drupal on ASE_.  Basically, just stack the different solutions in sub-folders.

Thoughts?

**Comment by haithamshahin333** [comment]
@rickrain thanks for reviewing! I like the idea you have of making it sub folders for different deployment strategies (example: standard plan that is public, ASE V3, Premium Plan with Private Endpoint, etc.) and making those each a sub folder and refactoring the README to be something like "Drupal on App Services" and you pick your deployment by the sub folder. Let me know if I'm following and I can update this PR with those sub folders and a refactored README.

**Comment by rickrain** [comment]
Yep, that sounds perfect!

**Comment by haithamshahin333** [comment]
@rickrain PR is updated per comments above! Appreciate the review

**Pull request merged**
